--- 
- hosts: all 
  become: true 
  tasks: 
   - name: Configure the remote repos 
     ansible.builtin.shell: | 
       sudo swapoff -a 
       sudo apt install -y curl gnupg2 software-properties-common apt-transport-https cacertificates 
       sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmour -o /etc/apt/trusted.gpg.d/docker.gpg 
       echo | sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" 
       sudo apt update -y 
 
   - name: Install ContainerD 
     ansible.builtin.shell: | 
       sudo apt install -y containerd.io 
       containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1 
       sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml 
       sudo systemctl restart containerd 
       sudo systemctl enable containerd 
 
   - name: Configure certificates 
     ansible.builtin.shell: | 
       sudo apt-get update 
       sudo apt-get install -y apt-transport-https ca-certificates curl gpg 
       curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg 
       echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list 
       sudo apt-get update -y 
 
   - name: kubelet, kubeadm, kubectl configuration 
     ansible.builtin.shell: | 
       sudo apt-get install -y kubelet kubeadm kubectl 
       sudo apt-mark hold kubelet kubeadm kubectl 
       sudo systemctl enable --now kubelet 
 
   - name: Troubleshooting fixes 
     ansible.builtin.shell: | 
       tee /etc/modules-load.d/containerd.conf <<EOF 
       br_netfilter 
       EOF 
       modprobe br_netfilter 
       tee /etc/sysctl.d/kubernetes.conf<<EOF 
       net.bridge.bridge-nf-call-ip6tables = 1 
       net.bridge.bridge-nf-call-iptables = 1 
       net.ipv4.ip_forward = 1 
       EOF 
 
   - name: kubeadm init 
     ansible.builtin.shell: | 
       sysctl --system 
       kubeadm init 
 
   - name: calico setup 
     ansible.builtin.shell: | 
       mkdir -p $HOME/.kube 
       sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config 
       sudo chown $(id -u):$(id -g) $HOME/.kube/config 
